INSERT INTO POC_STATUS_PROCESSO_SCRAPING (COD_STATUS_PROCESSO_SCRAPING, DES_STATUS) VALUES (1, 'A CARREGAR');
INSERT INTO POC_STATUS_PROCESSO_SCRAPING (COD_STATUS_PROCESSO_SCRAPING, DES_STATUS) VALUES (2, 'CARREGADO');
INSERT INTO POC_STATUS_PROCESSO_SCRAPING (COD_STATUS_PROCESSO_SCRAPING, DES_STATUS) VALUES (3, 'CADASTRADO PROCESSO');