
INSERT INTO PROCESSUM.POC_OCORRENCIA (
ID_POC_OCORRENCIA, STS_POC_OCORRENCIA, DTC_POC_OCORRENCIA, NUM_PROCESSO, NUM_CPF_CNPJ, NUM_LINHA, DTC_INICIO_PESQUISA, DTC_FIM_PESQUISA, NOM_CLIENTE, NOM_CONTA, DTC_CADASTRO, NOM_TIPO_CONTA, NOM_TIPO_ASSINATURA, STS_ASSINATURA, DES_ENDERECO_CORRESPONDENCIA, DES_ENDERECO_TRIBUTACAO, VAL_SALDO, NOM_FORMA_PAGAMENTO) 
VALUES
(PROCESSUM.SEQ_POC_OCORRENCIA.NEXTVAL, 'CADASTRADO', SYSDATE, '123456789', '11111111111', '7130303030', TO_DATE('01/01/2017', 'DD/MM/YYYY'), TO_DATE('31/01/2017', 'DD/MM/YYYY'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PROCESSUM.POC_OCORRENCIA (
ID_POC_OCORRENCIA, STS_POC_OCORRENCIA, DTC_POC_OCORRENCIA, NUM_PROCESSO, NUM_CPF_CNPJ, NUM_LINHA, DTC_INICIO_PESQUISA, DTC_FIM_PESQUISA, NOM_CLIENTE, NOM_CONTA, DTC_CADASTRO, NOM_TIPO_CONTA, NOM_TIPO_ASSINATURA, STS_ASSINATURA, DES_ENDERECO_CORRESPONDENCIA, DES_ENDERECO_TRIBUTACAO, VAL_SALDO, NOM_FORMA_PAGAMENTO) 
VALUES
(PROCESSUM.SEQ_POC_OCORRENCIA.NEXTVAL, 'CADASTRADO', SYSDATE, '123456789', '11111111111', '7130303030', TO_DATE('01/01/2017', 'DD/MM/YYYY'), TO_DATE('31/01/2017', 'DD/MM/YYYY'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PROCESSUM.POC_OCORRENCIA (
ID_POC_OCORRENCIA, STS_POC_OCORRENCIA, DTC_POC_OCORRENCIA, NUM_PROCESSO, NUM_CPF_CNPJ, NUM_LINHA, DTC_INICIO_PESQUISA, DTC_FIM_PESQUISA, NOM_CLIENTE, NOM_CONTA, DTC_CADASTRO, NOM_TIPO_CONTA, NOM_TIPO_ASSINATURA, STS_ASSINATURA, DES_ENDERECO_CORRESPONDENCIA, DES_ENDERECO_TRIBUTACAO, VAL_SALDO, NOM_FORMA_PAGAMENTO) 
VALUES
(PROCESSUM.SEQ_POC_OCORRENCIA.NEXTVAL, 'CADASTRADO', SYSDATE, '99999', '22222222222', '7131313131', TO_DATE('01/01/2017', 'DD/MM/YYYY'), TO_DATE('31/01/2017', 'DD/MM/YYYY'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PROCESSUM.POC_OCORRENCIA (
ID_POC_OCORRENCIA, STS_POC_OCORRENCIA, DTC_POC_OCORRENCIA, NUM_PROCESSO, NUM_CPF_CNPJ, NUM_LINHA, DTC_INICIO_PESQUISA, DTC_FIM_PESQUISA, NOM_CLIENTE, NOM_CONTA, DTC_CADASTRO, NOM_TIPO_CONTA, NOM_TIPO_ASSINATURA, STS_ASSINATURA, DES_ENDERECO_CORRESPONDENCIA, DES_ENDERECO_TRIBUTACAO, VAL_SALDO, NOM_FORMA_PAGAMENTO) 
VALUES
(PROCESSUM.SEQ_POC_OCORRENCIA.NEXTVAL, 'CADASTRADO', SYSDATE, '99999', '22222222222', '7131313131', TO_DATE('01/02/2017', 'DD/MM/YYYY'), TO_DATE('04/02/2017', 'DD/MM/YYYY'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PROCESSUM.POC_OCORRENCIA (
ID_POC_OCORRENCIA, STS_POC_OCORRENCIA, DTC_POC_OCORRENCIA, NUM_PROCESSO, NUM_CPF_CNPJ, NUM_LINHA, DTC_INICIO_PESQUISA, DTC_FIM_PESQUISA, NOM_CLIENTE, NOM_CONTA, DTC_CADASTRO, NOM_TIPO_CONTA, NOM_TIPO_ASSINATURA, STS_ASSINATURA, DES_ENDERECO_CORRESPONDENCIA, DES_ENDERECO_TRIBUTACAO, VAL_SALDO, NOM_FORMA_PAGAMENTO) 
VALUES
(PROCESSUM.SEQ_POC_OCORRENCIA.NEXTVAL, 'CADASTRADO', SYSDATE, '8888', '33333333333', '71999999999', TO_DATE('01/01/2017', 'DD/MM/YYYY'), TO_DATE('31/01/2017', 'DD/MM/YYYY'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PROCESSUM.POC_OCORRENCIA (
ID_POC_OCORRENCIA, STS_POC_OCORRENCIA, DTC_POC_OCORRENCIA, NUM_PROCESSO, NUM_CPF_CNPJ, NUM_LINHA, DTC_INICIO_PESQUISA, DTC_FIM_PESQUISA, NOM_CLIENTE, NOM_CONTA, DTC_CADASTRO, NOM_TIPO_CONTA, NOM_TIPO_ASSINATURA, STS_ASSINATURA, DES_ENDERECO_CORRESPONDENCIA, DES_ENDERECO_TRIBUTACAO, VAL_SALDO, NOM_FORMA_PAGAMENTO) 
VALUES
(PROCESSUM.SEQ_POC_OCORRENCIA.NEXTVAL, 'CADASTRADO', SYSDATE, '7777', '44444444444', '71999998888', TO_DATE('01/01/2016', 'DD/MM/YYYY'), TO_DATE('31/12/2016', 'DD/MM/YYYY'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT;