CREATE TABLE POC_STATUS_PROCESSO_SCRAPING(
	COD_STATUS_PROCESSO_SCRAPING	NUMBER	NOT NULL,
	DES_STATUS						VARCHAR2(50),
	CONSTRAINT PK_COD_ST_PR_SCRAPING PRIMARY KEY (COD_STATUS_PROCESSO_SCRAPING)
);

CREATE TABLE POC_PROCESSO_SCRAPING(
	DES_NUM_PROCESSO				VARCHAR2(200) NOT NULL,
	COD_STATUS_PROCESSO_SCRAPING	NUMBER	NOT NULL,
	DES_CANAL						VARCHAR2(200) NULL,
	DES_AREA						VARCHAR2(200) NULL,
	DES_ASSUNTO						VARCHAR2(200) NULL,
	DES__OUTROS_ASSUNTOS			VARCHAR2(200) NULL,
	DES_DISTRIBUICAO				VARCHAR2(200) NULL,
	DES_CONTROLE					VARCHAR2(200) NULL,
	DES_JUIZ						VARCHAR2(200) NULL,
	DES_VALOR_ACAO					VARCHAR2(100) NULL,
	DES_ADVOGADO					VARCHAR2(200) NULL,
	DES_REQUERENTE					VARCHAR2(200) NULL,
	DES_REQUERIDO					VARCHAR2(200) NULL,
	CONSTRAINT PK_NUM_PROCESSO PRIMARY KEY (DES_NUM_PROCESSO),
	CONSTRAINT FK_ST_PROC_SCRAPING_PROCESSO
    FOREIGN KEY (COD_STATUS_PROCESSO_SCRAPING)
    REFERENCES POC_STATUS_PROCESSO_SCRAPING (COD_STATUS_PROCESSO_SCRAPING)
);

CREATE TABLE PROCESSUM.POC_PROCESSO (
	ID_POC_PROCESSO  NUMBER(38,0) NOT NULL,
	COD_EMPRESA  NUMBER(38,0) NULL,
	NOM_EMPRESA  VARCHAR2(60) NULL,
	COD_NATUREZA  NUMBER(38,0) NULL,
	DES_NATUREZA  VARCHAR2(40) NULL,
	COD_ESPECIFICACAO_NATUREZA  NUMBER(38,0) NULL,
	DES_ESPECIFICACAO_NATUREZA  VARCHAR2(40) NULL,
	COD_DETALHE_ESPECIFIC_NATUREZA  NUMBER(38,0) NULL,
	NOM_DETALHE_ESPECIFIC_NATUREZA  VARCHAR2(60) NULL,
	COD_PRE_OBJETO_EMPRESA  NUMBER NULL,
	NOM_PRE_OBJETO_EMPRESA  VARCHAR2(50) NULL,
	DTC_CITACAO  DATE NULL,
	DTC_PROTOCOLO_AFORAMENTO  DATE NULL,
	STS_PASSOU_CALL_CENTER  VARCHAR2(1) NULL,
	STS_RELEVANTE  VARCHAR2(1) NULL,
	STS_CONSUMERISTA  VARCHAR2(1) NULL,
	STS_PASSOU_PROCON  VARCHAR2(1) NULL,
	NOM_TIPO_ACAO_PROCESSO  VARCHAR2(255) NULL,
	COD_DIVISAO_PROCESSO  NUMBER NULL,
	NOM_DIVISAO  VARCHAR2(50) NULL,
	NUM_PROCESSO  VARCHAR2(200) NULL,
	DTC_ENVIO_ESC_CONTRATADO  DATE NULL,
	COD_TIPO_ACAO_PROCESSO  NUMBER(38,0) NULL,
	COD_TIPO_ACAO  NUMBER(38,0) NULL,
	DES_TIPO_ACAO  VARCHAR2(70) NULL,
	SIG_ESCRITORIO_CONTRATADO  VARCHAR2(4 BYTE) NULL,
	NOM_ESCRITORIO_CONTRATADO  VARCHAR2(50) NULL,
	SIG_ESTADO  VARCHAR2(2 BYTE) NULL,
	NOM_ESTADO  VARCHAR2(300) NULL,
	SIG_MUNICIPIO  VARCHAR2(100) NULL,
	NOM_MUNICIPIO  VARCHAR2(45) NULL,
	COD_COMARCA  NUMBER(38,0) NULL,
	NOM_COMARCA  VARCHAR2(45) NULL,
	COD_JUIZO  NUMBER(38,0) NULL,
	NOM_JUIZO  VARCHAR2(80) NULL,
	SIG_ADVOGADO  VARCHAR2(10) NULL,
	NOM_ADVOGADO  VARCHAR2(100) NULL,
	SIG_CORRESPONSAVEL  VARCHAR2(10) NULL,
	NOM_CORRESPONSAVEL  VARCHAR2(100) NULL,
	NOM_POLO_ATIVO  VARCHAR2(4000) NULL,
	NOM_POLO_PASSIVO  VARCHAR2(4000) NULL,
	NOM_TERCEIRO_INTERESSADO  VARCHAR2(4000) NULL,
	CONSTRAINT PK_ID_POC_PROCESSO PRIMARY KEY (ID_POC_PROCESSO)
);

CREATE SEQUENCE PROCESSUM.SEQ_POC_PROCESSO
	MINVALUE 1
	MAXVALUE 9999999999
	START WITH     1
	INCREMENT BY   1
	NOCACHE
	NOCYCLE;

CREATE TABLE PROCESSUM.POC_OCORRENCIA (	
	ID_POC_OCORRENCIA NUMBER(38,0) NOT NULL ENABLE, 
	STS_POC_OCORRENCIA VARCHAR2(200 BYTE), 
	DTC_POC_OCORRENCIA DATE DEFAULT SYSDATE, 
	NUM_PROCESSO VARCHAR2(200 BYTE), 
	NUM_CPF_CNPJ VARCHAR2(20 BYTE), 
	NUM_LINHA VARCHAR2(20 BYTE), 
	DTC_INICIO_PESQUISA DATE, 
	DTC_FIM_PESQUISA DATE, 
	NOM_CLIENTE VARCHAR2(200 BYTE), 
	NOM_CONTA VARCHAR2(200 BYTE), 
	DTC_CADASTRO DATE, 
	NOM_TIPO_CONTA VARCHAR2(200 BYTE), 
	NOM_TIPO_ASSINATURA VARCHAR2(200 BYTE), 
	STS_ASSINATURA VARCHAR2(1 BYTE), 
	DES_ENDERECO_CORRESPONDENCIA VARCHAR2(1000 BYTE), 
	DES_ENDERECO_TRIBUTACAO VARCHAR2(1000 BYTE), 
	VAL_SALDO VARCHAR2(100 BYTE), 
	NOM_FORMA_PAGAMENTO VARCHAR2(200 BYTE), 	
	CONSTRAINT PK_ID_POC_OCORRENCIA PRIMARY KEY (ID_POC_OCORRENCIA)
);